In [1]:
import numpy as np

In [2]:
# Reading in the datasets
clean_dataset = np.loadtxt('Dataset/clean_dataset.txt')
noisy_dataset = np.loadtxt('Dataset/noisy_dataset.txt')

In [3]:
print(clean_dataset.shape)

(2000, 8)


In [4]:
print(noisy_dataset.shape)

(2000, 8)


In [6]:
print(clean_dataset[1:5][2:4])

[[-61. -60. -68. -62. -77. -90. -80.   1.]
 [-63. -65. -60. -63. -77. -81. -87.   1.]]


In [9]:
np.unique(clean_dataset[:, -1])

array([1., 2., 3., 4.])

In [16]:
nique, counts = np.unique(clean_dataset[:,-1], return_counts=True)
# result = dict(zip(clean_dataset, counts))
print(len(nique))
print(counts)

4
[500 500 500 500]


In [17]:
# Placeholder function to calculate entropy
def cal_entropy(dataset):

    nique, counts = np.unique(dataset[:,-1], return_counts=True)

    pk_values = []

    # calculating pk values
    for k in range(len(nique)):
        pk = counts[k]/len(dataset[:, -1])
        pk_values.append(pk)

    entropy = 0
    # calculating entropy based on pk values
    for pk in pk_values:
        entropy += (pk * np.log2(pk))

    return -1 * entropy

In [18]:
# Function to calculate the best split feature and value
# We will iterate through all possible split points
def find_split(dataset):

    # Initialisation
    best_info_gain = -9999
    best_feature_index = None
    best_feature_value = None

    entropy_complete_dataset = cal_entropy(dataset)

    # Loop through all features
    for feature_index in range(dataset.shape[1]-1):
        # Get unique feature values
        unique_feature_values = np.unique(dataset[:,feature_index])

        # Find all potential split points (midpoint between the values)
        potential_splits = []

        for i in range(len(unique_feature_values)-1):
            current_value = unique_feature_values[i]
            next_value = unique_feature_values[i+1]

            mid_value = (current_value+next_value)/2

            potential_splits.append(mid_value)

        for split_value in potential_splits:
            left_dataset_list = []
            right_dataset_list = []

            for row in dataset:
                if row[feature_index] <= split_value:
                    left_dataset_list.append(row)
                else:
                    right_dataset_list.append(row)
            
            left_dataset = np.array(left_dataset_list)
            right_dataset = np.array(right_dataset_list)

            prob_left = len(left_dataset) / len(dataset)
            prob_right = len(right_dataset) / len(dataset)

            information_gain = entropy_complete_dataset - (prob_left * cal_entropy(left_dataset) + (prob_right * cal_entropy(right_dataset)))
 
            if information_gain > best_info_gain:
                best_info_gain = information_gain
                best_feature_index = best_feature_index
                best_value = best_feature_value

    return best_info_gain, best_feature_index, best_feature_value

In [23]:
print(cal_entropy(np.array([[1],[1],[1],[2],[2],[3],[3],[3],[4],[4]])))

1.9709505944546686


In [29]:
print(cal_entropy(np.array([[2],[2],[2],[2],[2]])) == 0)


True


In [ ]:
# Our node class
class Node:
  def __init__(self, left = None, right = None, splitValue = None, isLeaf = False, prediction = None) -> None:
    self.left = left
    self.right = right
    self.isLeaf = isLeaf
    self.splitValue = splitValue
    self.prediction = prediction

In [ ]:
def decision_tree_learning(dataset, depth):

    
    
    if cal_entropy(dataset) == 0:
        nique, counts = np.unique(clean_dataset[:,-1], return_counts=True)
        leafNode = Node(isLeaf=True, prediction=counts[0])
        return leafNode
    
    split = find_split(dataset)

    # Best feature index 
    # best info gain
    # best feature value
    node = Node()

# result = dict(zip(clean_dataset, counts))
print(len(nique))
print(counts)
    